name = input("whats ur name? ")
print("hello", name + "!")

print("lets do some math (:")
number1 = input("insert first number: ")
number2 = input("insert second number: ")

print(number1, "+", number2, "=")
print(int(number1) + int(number2))
print(number1, "-", number2, "=")
print(int(number1) - int(number2))
print(number1, "*", number2, "=")
print(int(number1) * int(number2))
print(number1, "/", number2, "=")
print(int(number1) / int(number2))
print(number1, "**", number2, "=")
print(int(number1) ** int(number2))

print("tell me ur pet's name")
petname = input("insert pet's name: ")
print("whats ur favorite color?")
color = input("insert color: ")
print("whats ur favorite food?")
food = input("insert food: ")   
print("whats ur favorite drink?")
drink = input("insert drink: ")
print("whats ur favorite animal?")
animal = input("insert animal: ")

print("thanks for answering my questions! :D")