name = input("whats ur name? ")
surname = input("whats ur surname? ")
age = input("whats ur age? ")
print("hello", name + " " + surname + "!" + " ur age is " + age + "!")
print("lets do some math (:")
number1 = input("insert first number: ")
number2 = input("insert second number: ")
number3 = input("insert third number: ")
number4 = input("insert fourth number: ")
number5 = input("insert fifth number: ")
print(number1, "+", number2, "+", number3, "+", number4, "+", number5, "=")
print(int(number1) + int(number2) + int(number3) + int(number4) + int(number5))
print(number1, "-", number2, "-", number3, "-", number4, "-", number5, "=")
print(int(number1) - int(number2) - int(number3) - int(number4) - int(number5))
print(number1, "*", number2, "*", number3, "*", number4, "*", number5, "=")
print(int(number1) * int(number2) * int(number3) * int(number4) * int(number5))
print(number1, "/", number2, "/", number3, "/", number4, "/", number5, "=")
print(int(number1) / int(number2) / int(number3) / int(number4) / int(number5))
print(number1, "**", number2, "**", number3, "**", number4, "**", number5, "=")
print(int(number1) ** int(number2) ** int(number3) ** int(number4) ** int(number5))
