num = int(input("enter number: "))
if num > 10:
    print("you are right")
a = int(input("enter first number: "))
b = int(input("enter second number: "))

print(f"{a} + {b} =", a + b)
print(f"{a} - {b} =", a - b)
print(f"{a} * {b} =", a * b)
print(f"{a} / {b} =", a / b)
print(f"{a} % {b} =", a % b)
print(f"{a} ** {b} =", a ** b)
print(f"{a} < {b} =", a < b)
print(f"{a} > {b} =", a > b)
print(f"{a} <= {b} =", a <= b)
print(f"{a} >= {b} =", a >= b)
print(f"{a} == {b} =", a == b)
print(f"{a} != {b} =", a != b)
